version: "3.7"

services:
    personal_server:
        image: hmello/personal_server
        container_name: personal_server
        environment:
            - VIRTUAL_HOST=henriquemello.com
            - LETSENCRYPT_HOST=henriquemello.com
    nginx_proxy:
        image: jwilder/nginx-proxy
        container_name: nginx_proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ssl_certs:/etc/nginx/certs
            - vhost:/etc/nginx/vhost.d
            - nginx_html:/usr/share/nginx/html
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ssl_certs:/etc/nginx/certs
            - vhost:/etc/nginx/vhost.d
            - nginx_html:/usr/share/nginx/html
        environment:
            - DEFAULT_EMAIL=server@henriquemello.com
            - NGINX_PROXY_CONTAINER=nginx_proxy

volumes:
    ssl_certs:
    vhost:
    nginx_html:
